import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import { Inter } from "@next/font/google";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [category, setCategory] = useState({ category: "all" });

  useEffect(() => {
    console.log(category);

    fetch("/api/supabase")
      .then((res) => res.json())
      .then((data) => console.log(data));
      
  }, [category]);

  return (
    <>
      <Head>
        <title>Curations - Stunning Tools, served daily</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pl-[5%] pr-[5%]">
        <Navigation setCategory={setCategory} />
      </main>
    </>
  );
}
